#pragma once

const DATA_OBJECT_MODIFY_FLAGS DOMF_PROCESS_INFO_FULL={
		CProcessInfo::MF_PROCESS_ID|CProcessInfo::MF_IMAGE_FILE_PATH|CProcessInfo::MF_IMAGE_FILE_TIME|CProcessInfo::MF_PUUSED_TIME|CProcessInfo::MF_PUUSED|CProcessInfo::MF_MEMORY_USED|CProcessInfo::MF_VIRTUAL_MEMORY_USED,
		0,
		0,
		0};
const DATA_OBJECT_MODIFY_FLAGS DOMF_PROCESS_INFO_LIST_FULL={
		CProcessInfo::MF_PROCESS_ID|CProcessInfo::MF_IMAGE_FILE_PATH|CProcessInfo::MF_IMAGE_FILE_TIME|CProcessInfo::MF_PUUSED_TIME|CProcessInfo::MF_PUUSED|CProcessInfo::MF_MEMORY_USED|CProcessInfo::MF_VIRTUAL_MEMORY_USED,
		CProcessInfoList::MF_LIST,
		0,
		0};
const DATA_OBJECT_MODIFY_FLAGS DOMF_SERVICE_INFO_FULL={
		CProcessInfo::MF_PROCESS_ID|CProcessInfo::MF_IMAGE_FILE_PATH|CProcessInfo::MF_IMAGE_FILE_TIME|CProcessInfo::MF_PUUSED_TIME|CProcessInfo::MF_PUUSED|CProcessInfo::MF_MEMORY_USED|CProcessInfo::MF_VIRTUAL_MEMORY_USED,
		0,
		CServiceInfo::MF_SERVICE_ID|CServiceInfo::MF_NAME|CServiceInfo::MF_TYPE|CServiceInfo::MF_WORK_DIR|CServiceInfo::MF_STARTUP_PARAM|CServiceInfo::MF_STATUS|CServiceInfo::MF_WORK_STATUS|CServiceInfo::MF_LAST_OPERATION|CServiceInfo::MF_LAST_STATUS_CHANGE_TIME|CServiceInfo::MF_RESTARTUP_TIME|CServiceInfo::MF_CONTROL_PIPE_NAME|CServiceInfo::MF_SHUTDOWN_CMD|CServiceInfo::MF_CHAR_SET|CServiceInfo::MF_OTHER_EXEC_FILE_LIST,
		0};
const DATA_OBJECT_MODIFY_FLAGS DOMF_SERVICE_INFO_LIST_FULL={
		CProcessInfo::MF_PROCESS_ID|CProcessInfo::MF_IMAGE_FILE_PATH|CProcessInfo::MF_IMAGE_FILE_TIME|CProcessInfo::MF_PUUSED_TIME|CProcessInfo::MF_PUUSED|CProcessInfo::MF_MEMORY_USED|CProcessInfo::MF_VIRTUAL_MEMORY_USED,
		0,
		CServiceInfo::MF_SERVICE_ID|CServiceInfo::MF_NAME|CServiceInfo::MF_TYPE|CServiceInfo::MF_WORK_DIR|CServiceInfo::MF_STARTUP_PARAM|CServiceInfo::MF_STATUS|CServiceInfo::MF_WORK_STATUS|CServiceInfo::MF_LAST_OPERATION|CServiceInfo::MF_LAST_STATUS_CHANGE_TIME|CServiceInfo::MF_RESTARTUP_TIME|CServiceInfo::MF_CONTROL_PIPE_NAME|CServiceInfo::MF_SHUTDOWN_CMD|CServiceInfo::MF_CHAR_SET|CServiceInfo::MF_OTHER_EXEC_FILE_LIST,
		CServiceInfoList::MF_LIST};
const DATA_OBJECT_MODIFY_FLAGS DOMF_SERVICE_INFO_LIST_FOR_CLIENT_FETCH={
		CProcessInfo::MF_PROCESS_ID|CProcessInfo::MF_IMAGE_FILE_PATH|CProcessInfo::MF_IMAGE_FILE_TIME|CProcessInfo::MF_PUUSED_TIME|CProcessInfo::MF_PUUSED|CProcessInfo::MF_MEMORY_USED|CProcessInfo::MF_VIRTUAL_MEMORY_USED,
		0,
		CServiceInfo::MF_SERVICE_ID|CServiceInfo::MF_NAME|CServiceInfo::MF_TYPE|CServiceInfo::MF_WORK_DIR|CServiceInfo::MF_STATUS|CServiceInfo::MF_WORK_STATUS|CServiceInfo::MF_RESTARTUP_TIME|CServiceInfo::MF_CHAR_SET,
		CServiceInfoList::MF_LIST};
const DATA_OBJECT_MODIFY_FLAGS DOMF_PROCESS_INFO_FOR_STATUS_FETCH={
		CProcessInfo::MF_PROCESS_ID|CProcessInfo::MF_PUUSED_TIME|CProcessInfo::MF_PUUSED|CProcessInfo::MF_MEMORY_USED|CProcessInfo::MF_VIRTUAL_MEMORY_USED,
		0,
		0,
		0};
const DATA_OBJECT_MODIFY_FLAGS DOMF_SERVICE_INFO_FOR_EDIT={
		CProcessInfo::MF_IMAGE_FILE_PATH,
		0,
		CServiceInfo::MF_SERVICE_ID|CServiceInfo::MF_NAME|CServiceInfo::MF_TYPE|CServiceInfo::MF_WORK_DIR|CServiceInfo::MF_STARTUP_PARAM|CServiceInfo::MF_RESTARTUP_TIME|CServiceInfo::MF_CONTROL_PIPE_NAME|CServiceInfo::MF_SHUTDOWN_CMD|CServiceInfo::MF_CHAR_SET|CServiceInfo::MF_OTHER_EXEC_FILE_LIST,
		0};
