#pragma once



enum MSG_RESULT
{
	MSG_RESULT_SUCCEED=0,
	MSG_RESULT_FILE_NOT_EXIST,
	MSG_RESULT_DIR_NOT_EXIST,
	MSG_RESULT_INVALID_SCRIPT,
	MSG_RESULT_ONE_SCRIPT_IS_EXCUTING,
	MSG_RESULT_SCRIPT_FILE_NOT_EXIST,
	MSG_RESULT_SCRIPT_FILE_READ_ERROR,
	MSG_RESULT_SERVICE_NOT_EXIST,
	MSG_RESULT_QUERY_SEQUENCE_ERROR,
	MSG_RESULT_QUERY_SIZE_TOO_BIG,
	MSG_RESULT_DATA_COMPRESS_ERROR,
	MSG_RESULT_FILE_WRITE_ERROR,
	MSG_RESULT_FILE_READ_ERROR,
	MSG_RESULT_SERVICE_ID_IS_USED,
	MSG_RESULT_SERVICE_TYPE_NOT_SUPPORT,

};


enum SERVICE_STATUS_TYPE
{
	SERVICE_STATUS_NONE,
	SERVICE_STATUS_STOP,
	SERVICE_STATUS_RUNNING,
	SERVICE_STATUS_SHUTDOWNNING,
	SERVICE_STATUS_STARTUPPING,

};


enum SERVICE_TYPE
{
	SERVICE_TYPE_NORMAL,
	SERVICE_TYPE_WIN_SERVICE,
	SERVICE_TYPE_DIRECTORY,
	SERVICE_TYPE_MAX,

};


enum SERVICE_OPERATION_TYPE
{
	SERVICE_OPERATION_NONE,
	SERVICE_OPERATION_STARTUP,
	SERVICE_OPERATION_SHUTDOWN,
	SERVICE_OPERATION_MAX,

};


enum FILE_ATTRIBUTE_FLAG
{
	FILE_ATTRIBUTE_FLAG_DIRECTORY=1,
	FILE_ATTRIBUTE_FLAG_CAN_EXEC=(1<<1),

};



const LPCTSTR g_szSERVICE_TYPE[4]={_T("普通服务"),_T("Windows服务"),_T("目录"),_T("")};

