#pragma once



enum MSG_RESULT
{
	MSG_RESULT_SUCCEED=0,
	MSG_RESULT_FAILED,
	MSG_RESULT_FILE_NOT_EXIST,
	MSG_RESULT_DIR_NOT_EXIST,
	MSG_RESULT_INVALID_SCRIPT,
	MSG_RESULT_ONE_SCRIPT_IS_EXCUTING,
	MSG_RESULT_SCRIPT_FILE_NOT_EXIST,
	MSG_RESULT_SCRIPT_FILE_READ_ERROR,
	MSG_RESULT_SERVICE_NOT_EXIST,
	MSG_RESULT_QUERY_SEQUENCE_ERROR,
	MSG_RESULT_QUERY_SIZE_TOO_BIG,
	MSG_RESULT_DATA_COMPRESS_ERROR,
	MSG_RESULT_FILE_WRITE_ERROR,
	MSG_RESULT_FILE_READ_ERROR,
	MSG_RESULT_SERVICE_ID_IS_USED,
	MSG_RESULT_SERVICE_TYPE_NOT_SUPPORT,
	MSG_RESULT_USER_NAME_OR_PASSWORD_ERROR,
	MSG_RESULT_CONTROL_PIPE_NOT_AVAILABLE,
	MSG_RESULT_SHUTDOWN_CMD_NOT_SET,
	MSG_RESULT_MAX,

};


enum SERVICE_STATUS_TYPE
{
	SERVICE_STATUS_NONE,
	SERVICE_STATUS_STOP,
	SERVICE_STATUS_RUNNING,
	SERVICE_STATUS_SHUTDOWNNING,
	SERVICE_STATUS_STARTUPPING,

};


enum SERVICE_TYPE
{
	SERVICE_TYPE_NORMAL,
	SERVICE_TYPE_WIN_SERVICE,
	SERVICE_TYPE_DIRECTORY,
	SERVICE_TYPE_MAX,

};


enum SERVICE_OPERATION_TYPE
{
	SERVICE_OPERATION_NONE,
	SERVICE_OPERATION_STARTUP,
	SERVICE_OPERATION_SHUTDOWN,
	SERVICE_OPERATION_MAX,

};


enum FILE_ATTRIBUTE_FLAG
{
	FILE_ATTRIBUTE_FLAG_DIRECTORY=1,
	FILE_ATTRIBUTE_FLAG_CAN_EXEC=(1<<1),

};


enum SERVICE_SHUTDOWN_TYPE
{
	SERVICE_SHUTDOWN_TYPE_NORMAL,
	SERVICE_SHUTDOWN_TYPE_FORCE,
	SERVICE_SHUTDOWN_TYPE_SAFE,

};



const LPCTSTR g_szMSG_RESULT[20]={_T("成功"),_T("失败"),_T("文件不存在"),_T("目录不存在"),_T("非法脚本"),_T("已有脚本在执行"),_T("脚本文件不存在"),_T("脚本文件读取错误"),_T("服务不存在"),_T("请求序列错误"),_T("请就数据过大"),_T("数据压缩错误"),_T("文件写入错误"),_T("文件读取错误"),_T("服务ID已被占用"),_T("服务类型不支持"),_T("用户名或密码错误"),_T("控制管道不可用"),_T("关服命令未设置"),_T("")};

const LPCTSTR g_szSERVICE_TYPE[4]={_T("普通服务"),_T("Windows服务"),_T("目录"),_T("")};

